title: Praveen Kumar Chalamcharla
logo: /assets/img/MyPic.jpg

description:
  <p align="center">
  <a href="docs/PraveenChalamcharla.docx">Resume</a> |
  <a href="https://linkedin.com/in/praveen-kumar-chalamcharla-06454b1b">LinkedIn</a> |
  <a href="https://github.com/praveen-2814">GitHub</a>
  
  <br>   
  I started working on Data Science and ML Projects.
  Pursuing Masters in ML & DS.
  I have been working as a Cloudera Platform Engineer for past 8+ years. 
  Also have development experience before I started working as platfomr Engineer.
  <br>
  </p>



theme: jekyll-theme-minimal
